# -*- coding: utf-8 -*-
"""synent-task1-datacleaning-beshoynashaat

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x9wEbtd8HC83ESF-UwkF2bDJAtfJw0sL
"""

import pandas as pd
import seaborn as sns

# Load the Titanic dataset
df = sns.load_dataset('titanic')

print('Initial Data Shape:', df.shape)
display(df.head())

"""### 1. Handling Missing Values

"""

# Check for missing values
print('Missing values per column:\n', df.isnull().sum())

# Fill 'age' with the median
df['age'] = df['age'].fillna(df['age'].median())

# Drop 'deck' since it has too many missing values
if 'deck' in df.columns:
    df = df.drop(columns=['deck'])

# Fill 'embarked' and 'embark_town' with the mode
df['embarked'] = df['embarked'].fillna(df['embarked'].mode()[0])
df['embark_town'] = df['embark_town'].fillna(df['embark_town'].mode()[0])

print("\nMissing Values is Filled")
print('\nMissing values after cleaning:\n', df.isnull().sum())

"""### 2. Remove Duplicates, Convert Data Types, and Rename Columns"""

# Remove duplicates
duplicates_count = df.duplicated().sum()
print(f'Number Of Duplicated columns: {duplicates_count}')
df = df.drop_duplicates()
print(f'Removed {duplicates_count} duplicate rows.')

# Convert data types (e.g., ensuring 'survived' is an integer/category)
df['survived'] = df['survived'].astype(int)

# Rename columns for clarity
df = df.rename(columns={
    'pclass': 'passenger_class',
    'sibsp': 'siblings_spouses',
    'parch': 'parents_children'
})

print('\nFinal columns:', df.columns.tolist())
display(df.head())